name: drivana
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  path: ^1.9.0
  lottie: ^3.1.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.1
  http: ^1.2.2
  flutter_stripe: ^11.0.0
  glassmorphism: ^3.0.0
  simple_animations: ^5.0.2
  flutter_spinkit: ^5.2.1
  vibration: ^2.0.0
  flutter_osm_plugin: ^1.2.1
  location: ^6.0.2
  shimmer: ^3.0.0
  flutter_tilt: ^2.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true # Ensure this is directly under flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

  # flutter_intl:
  #   enabled: true