// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoSwH4Of0PHFVkGVj2Yy0gMtH4xPvpCdQ',
    appId: '1:321139598212:web:2253f78f59dace7f1bf3d1',
    messagingSenderId: '321139598212',
    projectId: 'bmp280-3eefe',
    authDomain: 'bmp280-3eefe.firebaseapp.com',
    databaseURL: 'https://bmp280-3eefe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmp280-3eefe.firebasestorage.app',
    measurementId: 'G-HTYMN0DZ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHXTvwRjJlyCtvnEUSeKQi0JquYx6rmxA',
    appId: '1:321139598212:android:97a8f5b4da2b684f1bf3d1',
    messagingSenderId: '321139598212',
    projectId: 'bmp280-3eefe',
    databaseURL: 'https://bmp280-3eefe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmp280-3eefe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaLGERioTqOVOcFUFDL7Xay9ruiNbF-MU',
    appId: '1:321139598212:ios:6401c507ee2db7191bf3d1',
    messagingSenderId: '321139598212',
    projectId: 'bmp280-3eefe',
    databaseURL: 'https://bmp280-3eefe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmp280-3eefe.firebasestorage.app',
    iosClientId: '321139598212-q43hrrrmoqmmqeali5r132bshdj65jdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaLGERioTqOVOcFUFDL7Xay9ruiNbF-MU',
    appId: '1:321139598212:ios:6401c507ee2db7191bf3d1',
    messagingSenderId: '321139598212',
    projectId: 'bmp280-3eefe',
    databaseURL: 'https://bmp280-3eefe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmp280-3eefe.firebasestorage.app',
    iosClientId: '321139598212-q43hrrrmoqmmqeali5r132bshdj65jdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoSwH4Of0PHFVkGVj2Yy0gMtH4xPvpCdQ',
    appId: '1:321139598212:web:b7fddc9efa342b8c1bf3d1',
    messagingSenderId: '321139598212',
    projectId: 'bmp280-3eefe',
    authDomain: 'bmp280-3eefe.firebaseapp.com',
    databaseURL: 'https://bmp280-3eefe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmp280-3eefe.firebasestorage.app',
    measurementId: 'G-ZP0J89KGJK',
  );
}
